INSERT INTO counties (county_name, governor_name) VALUES
('Mombasa','Abdulswamad Nassir'),
('Kwale','Fatuma Achani'),
('Kilifi','Gideon Mung''aro'),
('Tana River','Dhadho Godhana'),
('Lamu','Issa Timamy'),
('Taita-Taveta','Andrew Mwadime'),
('Garissa','Nathif Jama'),
('Wajir','Ahmed Abdullahi'),
('Mandera','Mohamed Adan Khalif'),
('Marsabit','Mohamud Ali'),
('Isiolo','Abdi Guyo'),
('Meru','Isaac Mutuma'),
('Tharaka-Nithi','Muthomi Njuki'),
('Embu','Cecily Mbarire'),
('Kitui','Julius Malombe'),
('Machakos','Wavinya Ndeti'),
('Makueni','Mutula Kilonzo Jr.'),
('Nyandarua','Moses Kiarie Badilisha'),
('Nyeri','Mutahi Kahiga'),
('Kirinyaga','Anne Waiguru'),
('Murang''a','Irungu Kang''ata'),
('Kiambu','Kimani Wamatangi'),
('Turkana','Jeremiah Lomorukai'),
('West Pokot','Simon Kachapin'),
('Samburu','Jonathan Lelelit'),
('Trans Nzoia','George Natembeya'),
('Uasin Gishu','Jonathan Bii'),
('Elgeyo-Marakwet','Wesley Rotich'),
('Nandi','Stephen Sang'),
('Baringo','Benjamin Cheboi'),
('Laikipia','Joshua Irungu'),
('Nakuru','Susan Kihika'),
('Narok','Patrick Ntutu'),
('Kajiado','Joseph Ole Lenku'),
('Kericho','Eric Mutai'),
('Bomet','Hillary Barchok'),
('Kakamega','Fernandes Barasa'),
('Vihiga','Wilber Ottichilo'),
('Bungoma','Kenneth Lusaka'),
('Busia','Paul Otuoma'),
('Siaya','James Orengo'),
('Kisumu','Anyang'' Nyong''o'),
('Homa Bay','Gladys Wanga'),
('Migori','Ochilo Ayacko'),
('Kisii','Simba Arati'),
('Nyamira','Amos Nyaribo'),
('Nairobi','Johnson Sakaja');